test_add (skills.unittest_.unitest_demo.TestCaseFuncs)
test add func ... ok
test_div (skills.unittest_.unitest_demo.TestCaseFuncs)
test div func ... FAIL
test_upper (skills.unittest_.unitest_demo.TestCaseFuncs)
test upper func ... skipped '目前只测试数学功能的函数,该函数先跳过'

======================================================================
FAIL: test_div (skills.unittest_.unitest_demo.TestCaseFuncs)
test div func
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Learning\test-dev-skills\skills\unittest_\unitest_demo.py", line 59, in test_div
    self.assertEqual(div(1, 2), 0.5)
AssertionError: 0 != 0.5

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1, skipped=1)
